### ISSUE TITLE
Broken Pipe Errors

### ISSUE THREAD

**Issue by cledoux** [takluyver/bash_kernel#19] opened 2015-03-09 23:11 UTC
Using any type of non-trivial pipe prints a "Broken pipe" error.

For example, use the following code snippet:
`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;`

Executing in bash behaves as expected:

```
< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;
3JT1JUE_NE8-CcgaJXfkESNfWLgiVIWd
```

Executing in ipython (notebook or console both give same error):

```
In [1]: < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;
QgmPQRyp0u1Lllf6c4Y5mAE8FxM563A_tr: write error: Broken pipe
tr: write error
```

**Comment by RemiSlv** [comment] 2016-04-14 08:32
same errors here:
![image](https://cloud.githubusercontent.com/assets/16202262/14521908/72859eee-025e-11e6-8ed6-577871607fac.png)

I do get the results I need but the errors are somewhat annoying :)

**Comment by takluyver** [comment] 2016-04-14 11:49
I can reproduce it, but I have no idea what's going on with this.

**Comment by RemiSlv** [comment] 2016-04-14 14:24
looks like this should help:
https://docs.python.org/2/library/subprocess.html#replacing-shell-pipeline

although that will probably be a pain to manage nested commands such as `echo $(ls | grep something) | grep something`

**Comment by takluyver** [comment] 2016-04-14 14:40
The bash_kernel is not emulating bash in Python: it's actually running a bash shell in a separate process and sending your code to that.

**Comment by dborgesr** [comment] 2017-05-13 16:09
<img width="1107" alt="image" src="https://cloud.githubusercontent.com/assets/3431090/26027026/b5db8f44-37d4-11e7-9f25-fc1b6e35f6e3.png">

So i'm getting the same error as well, https://blog.nelhage.com/2010/02/a-very-subtle-bug/ is this what's causing it?

**Comment by takluyver** [comment] 2017-05-15 15:12
Aha, good find. I think that might well be it. Would you like to make a PR? pexpect's `spawn()` now takes a `preexec_fn` like subprocess.

**Comment by pgcudahy** [comment] 2018-12-28 09:47
I'm getting odd broken pipe errors too. Is this issue still open or could it be something new?

**Comment by kdm9** [comment] 2024-05-08 05:38
allegedly, this was fixed in #135, but please reopen if issues persist

**Closed by kdm9** 2024-05-08 05:38 UTC
