### ISSUE TITLE
.bashrc Seems to Cause the Kernel not to Work

### ISSUE THREAD

**Issue by joshlatto** [takluyver/bash_kernel#22] opened 2015-04-21 13:40 UTC
I have the following in my .bashrc:

```sh
\# .bashrc

\# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

\# User specific aliases and functions
I have a bunch of straightforward aliases, but I don't think they are causing the problem. They are all either database calls or things like rm='rm -i'. We suspect that the color changes in my prompt are the problem. 

#export PS1="[jlatto@Winterfell:\w $(date)]> "

#export PS1="[\t] \[\033[1;33m\]\u\[\033[0m\]@\h:\[\033[36m\][\w]:\[\033[0m\]> "
export PS1="[\t] \[\033[1;35m\] \u\[\033[0m\]@R\[\033[36m\] [\w]\[\033[0m\]> "
#export PS1="[\e]2;\w\a\e[31;40;1m]----------------------------------------------------------------------------------------------------------------------------------------------------------------\n)[\e[0m] ";
```

When I run the notebook server and open up a notebook with the Bash Kernel, nothing will run. If I comment out everything, and then relaunch the server it works fine. Please let me know if there is other information that would be useful. Thanks for looking into this!

**Comment by takluyver** [comment] 2015-04-21 16:39
For the moment, modifying PS1 causes it problems. This will be fixed when we get Pexpect 4 out, which I hope will be soon.

**Comment by monkey-code** [comment] 2016-01-03 14:05
After install the bash_kernel,I run it by 'ipython console --kernel bash',but  don't success:
Jupyter Console 4.0.3
[ZMQTerminalIPythonApp] Loading IPython extension: storemagic
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pexpect/expect.py", line 97, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.4/dist-packages/pexpect/pty_spawn.py", line 452, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/bash_kernel/__main__.py", line 3, in <module>
    IPKernelApp.launch_instance(kernel_class=BashKernel)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-121>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 384, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/kernelapp.py", line 323, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py", line 380, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/bash_kernel/kernel.py", line 46, in __init__
    self._start_bash()
  File "/usr/local/lib/python3.4/dist-packages/bash_kernel/kernel.py", line 55, in _start_bash
    self.bashwrapper = replwrap.bash()
  File "/usr/local/lib/python3.4/dist-packages/pexpect/replwrap.py", line 113, in bash
    extra_init_cmd="export PAGER=cat")
  File "/usr/local/lib/python3.4/dist-packages/pexpect/replwrap.py", line 51, in __init__
    prompt_change.format(new_prompt, continuation_prompt))
  File "/usr/local/lib/python3.4/dist-packages/pexpect/replwrap.py", line 61, in set_prompt
    self.child.expect(orig_prompt)
  File "/usr/local/lib/python3.4/dist-packages/pexpect/spawnbase.py", line 315, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python3.4/dist-packages/pexpect/spawnbase.py", line 339, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.4/dist-packages/pexpect/expect.py", line 104, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.4/dist-packages/pexpect/expect.py", line 68, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f95b3cd8828>
command: /bin/bash
args: ['/bin/bash', '--rcfile', '/usr/local/lib/python3.4/dist-packages/pexpect/bashrc.sh']
searcher: None
buffer (last 100 chars): 'root@311b47d44a05:~# '
before (last 100 chars): 'root@311b47d44a05:~# '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 187
child_fd: 34
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
ERROR: Kernel did not respond
Shutting down kernel

could you help me solve this problem？thank you!

**Comment by takluyver** [comment] 2016-01-04 11:11
@monkey-code can you try installing [pexpect from master](https://github.com/pexpect/pexpect)? We missed something, and we need to do a new release.

**Comment by monkey-code** [comment] 2016-01-04 11:54
@takluyver  Thank you ,my purpose is to use bash_kernel in jupyter,but the bash_kernel always died,so pexpect can't solve my problem.Do you mean this version of the bash_kernel in bug? Will there be a new version?

**Comment by takluyver** [comment] 2016-01-04 12:08
bash_kernel uses pexpect to run bash. I suspect that the issue you're seeing is because of a bug in Pexpect.

**Comment by monkey-code** [comment] 2016-01-04 14:42
@takluyver  Thank you very much,I updated the pexpect version and succeeded in solving the problem.

**Comment by takluyver** [comment] 2016-01-04 14:48
Thanks for confirming that did it. I'll try to arrange a new release of Pexpect.

Closing here since it's not a bug in bash_kernel.

**Closed by takluyver** 2016-01-04 14:48 UTC
